server {
    listen 80;
    server_name _;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name _;
    client_max_body_size 150m;

    ssl_certificate /Users/peterjaber/Desktop/Easyflow.io/Code/appsmith/app/client/docker/localhost.pem;
    ssl_certificate_key /Users/peterjaber/Desktop/Easyflow.io/Code/appsmith/app/client/docker/localhost-key.pem;

    # include /etc/letsencrypt/options-ssl-nginx.conf;
    # ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    gzip on;

    proxy_ssl_server_name on;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header Accept-Encoding "";

    sub_filter_once off;
    location / {
        proxy_pass http://localhost:3000;
    }


    location /api {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://localhost:8080;
    }

    location /oauth2 {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://localhost:8080;
    }

    location /login {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_pass http://localhost:8080;
    }
}
